
namespace: ""
odom_frame: "odom"
odom_topic: "testodom"
marker_topic: "trajectory_markers"


trajectory_reader_publisher_node:
  namespace: ""
  odom_frame: "odom"
  marker_topic: "trajectory_markers"